// AUTO-GENERATED FROM THE LUDOBOTICS LAUNCHER.
// Run `npm run sync:teacher-dashboard` after editing the launcher scenario.
// Do not edit this file directly.
export type OdysseyScenarioStep = {
  id: string;
  label: string;
  location: string;
  puzzleId?: string;
  requires?: {
    allOf?: string[];
  };
};

export type OdysseyScenarioChapter = {
  chapterId: string;
  title: string;
  steps: OdysseyScenarioStep[];
};

export type OdysseyScenario = {
  title: string;
  chapters: OdysseyScenarioChapter[];
};

export type OdysseyScenarioStepDetails = {
  imagePlaceholderLabel: string;
  imagePlaceholderSubtitle: string;
  teacherNote: string;
  futureContentItems: string[];
  accentBackground: string;
};

const futureContentItems = [
  "Screenshot or concept art for this area.",
  "Expected ROS 2 command pattern.",
  "Most common mistake for this checkpoint.",
  "Suggested teacher intervention.",
];

function hashScenarioValue(value: string): number {
  let hash = 0;
  for (let index = 0; index < value.length; index += 1) {
    hash = ((hash << 5) - hash + value.charCodeAt(index)) | 0;
  }
  return Math.abs(hash);
}

function scenarioStepAccent(stepId: string): string {
  const hue = hashScenarioValue(stepId) % 360;
  return `linear-gradient(135deg, hsl(${hue} 70% 36%), hsl(${(hue + 58) % 360} 66% 48%))`;
}

export function getOdysseyScenarioStepDetails(
  chapter: OdysseyScenarioChapter,
  step: OdysseyScenarioStep,
): OdysseyScenarioStepDetails {
  const puzzleText = step.puzzleId === undefined
    ? "This checkpoint tracks narrative and navigation progress."
    : `This checkpoint is linked to puzzle ${step.puzzleId}.`;

  return {
    imagePlaceholderLabel: step.location,
    imagePlaceholderSubtitle: "Area image placeholder",
    teacherNote: `${step.label} is a placeholder teacher note for ${chapter.title}. Replace this text with the intended learning objective, expected commands, common misconceptions, and intervention advice for this area. ${puzzleText}`,
    futureContentItems,
    accentBackground: scenarioStepAccent(step.id),
  };
}

export const odysseyScenario: OdysseyScenario = {
  title: "Odyssey Chapters 1-3",
  chapters: [
    {
      chapterId: "Ch1",
      title: "Chapter 1 - CLI",
      steps: [
        { id: "c1_s01", label: "Exterior", location: "Exterior", puzzleId: "P1.0" },
        { id: "c1_s02", label: "Entry Door", location: "Airlock ext.", puzzleId: "P1.1", requires: { allOf: ["c1_s01"] } },
        { id: "c1_s03", label: "Entering Spaceship", location: "Airlock ext.", puzzleId: "P1.1", requires: { allOf: ["c1_s02"] } },
        { id: "c1_s04", label: "Second door", location: "Airlock int.", puzzleId: "P1.2", requires: { allOf: ["c1_s03"] } },
        { id: "c1_s05", label: "Going to the Deck", location: "Floors 0, 3, 9", puzzleId: "P1.3", requires: { allOf: ["c1_s04"] } },
        { id: "c1_s06", label: "Argos Mission brief", location: "Floor 9", puzzleId: "P1.3", requires: { allOf: ["c1_s05"] } },
        { id: "c1_s07", label: "Battery Room", location: "Floor 5", puzzleId: "P1.4", requires: { allOf: ["c1_s06"] } },
        { id: "c1_s08", label: "Engine Room", location: "Floor -2", puzzleId: "P1.5", requires: { allOf: ["c1_s06"] } },
        { id: "c1_s09", label: "Server Maze Reach Button", location: "Floor 8", puzzleId: "P1.6", requires: { allOf: ["c1_s07", "c1_s08"] } },
        { id: "c1_s10", label: "System Reboot Signal", location: "Floor 8", puzzleId: "P1.7", requires: { allOf: ["c1_s09"] } },
      ],
    },
    {
      chapterId: "Ch2",
      title: "Chapter 2 - Packages, Nodes and Tools",
      steps: [
        { id: "c2_s01", label: "ARGOS Briefing", location: "Floor 9 Deck" },
        { id: "c2_s02", label: "Find RQT Package", location: "Floor 7 Elevator", requires: { allOf: ["c2_s01"] } },
        { id: "c2_s03", label: "Open CCR Door", location: "Floor 7 Elevator", puzzleId: "P2.1", requires: { allOf: ["c2_s02"] } },
        { id: "c2_s04", label: "Relay Camera to CCR", location: "CCR", puzzleId: "P2.2", requires: { allOf: ["c2_s03"] } },
        { id: "c2_s05", label: "Maintenance Bay Area 1", location: "Area 1", puzzleId: "P2.3", requires: { allOf: ["c2_s04"] } },
        { id: "c2_s06", label: "Maintenance Bay Area 2", location: "Area 2", puzzleId: "P2.4", requires: { allOf: ["c2_s05"] } },
        { id: "c2_s07", label: "Maintenance Bay Area 3", location: "Area 3", puzzleId: "P2.5", requires: { allOf: ["c2_s06"] } },
        { id: "c2_s08", label: "Maintenance Bay Area 4", location: "Area 4", puzzleId: "P2.6", requires: { allOf: ["c2_s07"] } },
        { id: "c2_s09", label: "Maintenance Bay Area 5", location: "Area 5", puzzleId: "P2.7", requires: { allOf: ["c2_s08"] } },
        { id: "c2_s10", label: "Server Vault Connect", location: "CCR", requires: { allOf: ["c2_s09"] } },
        { id: "c2_s11", label: "Secure Vault Challenge", location: "Secure Vault", puzzleId: "P2.8", requires: { allOf: ["c2_s10"] } },
        { id: "c2_s12", label: "Return to ARGOS", location: "CCR", requires: { allOf: ["c2_s11"] } },
        { id: "c2_s13", label: "Deck Transition to Ch3", location: "Floor 9 Deck", requires: { allOf: ["c2_s12"] } },
      ],
    },
    {
      chapterId: "Ch3",
      title: "Chapter 3 - Launch Files and Robot Control",
      steps: [
        { id: "c3_s01", label: "ARGOS Chapter 3 Briefing", location: "Floor 9 Deck" },
        { id: "c3_s02", label: "Launch System Discovery", location: "Robotics Lab", requires: { allOf: ["c3_s01"] } },
        { id: "c3_s03", label: "First Launch File", location: "Robotics Lab", puzzleId: "P3.1", requires: { allOf: ["c3_s02"] } },
        { id: "c3_s04", label: "Robot Teleoperation", location: "Testing Arena", puzzleId: "P3.2", requires: { allOf: ["c3_s03"] } },
        { id: "c3_s05", label: "Sensor Topic Check", location: "Testing Arena", puzzleId: "P3.3", requires: { allOf: ["c3_s04"] } },
        { id: "c3_s06", label: "Navigation Node Startup", location: "Navigation Bay", puzzleId: "P3.4", requires: { allOf: ["c3_s05"] } },
        { id: "c3_s07", label: "Multi-node Launch", location: "Navigation Bay", puzzleId: "P3.5", requires: { allOf: ["c3_s06"] } },
        { id: "c3_s08", label: "Final System Validation", location: "Control Room", puzzleId: "P3.6", requires: { allOf: ["c3_s07"] } },
      ],
    },
  ],
};
